[package]
name = "dao-core"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = true }

[dev-dependencies]
pretty_assertions = "1"
tempfile = "3"
